'use client';

import * as React from 'react';

export type Language = 'en' | 'mm';

interface LanguageContextValue {
  language: Language;
  setLanguage: (value: Language) => void;
}

const LanguageContext = React.createContext<LanguageContextValue | undefined>(
  undefined
);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = React.useState<Language>('en');

  React.useEffect(() => {
    if (typeof window === 'undefined') return;
    const stored = window.localStorage.getItem('tmyg-lang') as Language | null;
    if (stored === 'en' || stored === 'mm') {
      setLanguage(stored);
      document.documentElement.lang = stored === 'en' ? 'en' : 'my';
    }
  }, []);

  React.useEffect(() => {
    if (typeof window === 'undefined') return;
    window.localStorage.setItem('tmyg-lang', language);
    document.documentElement.lang = language === 'en' ? 'en' : 'my';
  }, [language]);

  const value = React.useMemo(
    () => ({ language, setLanguage }),
    [language]
  );

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const ctx = React.useContext(LanguageContext);
  if (!ctx) {
    throw new Error('useLanguage must be used within LanguageProvider');
  }
  return ctx;
}

const translations = {
  en: {
    appName: 'The More You Glow By Ingyin POS',
    appShort: 'The More You Glow By Ingyin',
    dashboardSubtitle: 'POS Dashboard',
    loginBadge: 'Sign in to The More You Glow By Ingyin',
    loginHeading: 'Welcome back',
    loginButton: 'Sign in',
    loginEmail: 'Email',
    loginPassword: 'Password',
    dashboardOverview: 'Overview',
    dashboardSubtext: 'Daily, monthly, and yearly performance at a glance.',
    inventoryTitle: 'Inventory',
    inventorySubtext: 'Manage products, prices, and stock levels.',
    addProduct: 'Add product',
    searchInventoryPlaceholder: 'Search by name, category, or barcode...',
    exportInventory: 'Export to Excel',
    exportRecent: 'Export Recently Added',
    downloadTemplate: 'Download Template',
    uploadCsv: 'Upload CSV',
    recentlyAdded: 'Recently Added',
    itemCount: 'items',
    syncing: 'Syncing changes...',
    productId: 'ID',
    image: 'Image',
    name: 'Name',
    sku: 'SKU',
    category: 'Category',
    size: 'Size',
    barcode: 'Barcode',
    stock: 'Stock',
    salePrice: 'Sale Price',
    actions: 'Actions',
    scanBarcode: 'Scan Barcode',
    bulkUpload: 'Bulk Upload',
    onlineSyncReady: 'Online sync ready.',
    offlineSyncLater: 'Offline mode. Changes will sync later.',
    customersTitle: 'Customers',
    customersSubtext: 'Manage customer profiles and loyalty status.',
    addCustomer: 'Add customer',
    edit: 'Edit',
    delete: 'Delete',
    phone: 'Phone',
    phone2: 'Phone 2',
    facebook: 'Facebook',
    address: 'Address',
    remark: 'Remark',
    totalSpent: 'Total Spent',
    loyalty: 'Loyalty',
    yes: 'Yes',
    no: 'No',
    schemaCacheWait: 'facebook_username column cache is not refreshed yet. Please retry in a moment.',
    menuMain: 'Main Menu',
    menuCrm: 'CRM',
    menuSettingsSection: 'Settings',
    menuDashboard: 'Dashboard',
    menuPos: 'POS',
    menuInventory: 'Inventory',
    menuShopSales: 'Shop Sales Log',
    menuDeliverySales: 'Delivery Sales Log',
    menuCustomers: 'Customers',
    menuSettings: 'Settings',
    menuLogout: 'Log out',
    downloadExcel: 'Download Excel',
    refresh: 'Refresh',
    searchSalesPlaceholder: 'Search invoice, customer, phone, payment...',
    searchDeliveryPlaceholder: 'Search invoice, customer, courier, phone...',
    monthFilter: 'Month',
    shopSalesLogTitle: 'Shop Sales Log',
    deliverySalesLogTitle: 'Delivery Sales Log',
    summaryByPayment: 'Summary (By Payment Method)',
    summary: 'Summary',
    dailyTotal: 'Daily Total',
    daily: 'Daily',
    monthly: 'Monthly',
    yearly: 'Yearly',
    allCouriers: 'All Couriers',
    date: 'Date',
    invoice: 'Invoice',
    customer: 'Customer',
    courier: 'Courier',
    deliveryFee: 'Delivery Fee',
    paymentMethod: 'Payment Method',
    status: 'Status',
    totalAmount: 'Total Amount',
    itemsSummary: 'Items (Summary)',
    collected: 'Collected',
    netSale: 'Net Sale',
    courierFees: 'Courier Fees',
    couriers: 'Couriers',
    totalLabel: 'Total',
    noSalesRecords: 'No sales records found.',
    noDeliveryRecords: 'No delivery records found.',
    noSummary: 'No summary available.',
    action: 'Action',
    accessRestricted: 'Access restricted.',
    salesAdminOnly: 'Sales reports are available to admins only.',
    subtotal: 'Subtotal',
    dateRange: 'Date Range',
    totalSales: 'Total Sales',
    totalFees: 'Total Fees',
    number: 'No.',
    phoneRequired: 'Phone is required.',
    accessRestrictedSignIn: 'Access restricted. Please sign in to continue.',
    all: 'All',
    close: 'Close',
    save: 'Save',
    saving: 'Saving...',
    deleteConfirmCustomerTitle: 'Delete customer?',
    deleteConfirmCustomerDesc: 'Are you sure you want to delete this customer?',
    deleting: 'Deleting...',
    customerFormTitleEdit: 'Edit Customer',
    customerFormTitleAdd: 'Add Customer',
    customerFormSubtext: 'Manage customer details and loyalty status.',
    phonePlaceholder: 'Phone number',
    phone2Placeholder: 'Secondary phone',
    customerNamePlaceholder: 'Customer name',
    addressPlaceholder: 'Address',
    facebookPlaceholder: 'Facebook user name',
    notesPlaceholder: 'Notes',
    loyalStatus: 'Loyal Status',
    standard: 'Standard',
    loyal: 'Loyal',
    cancel: 'Cancel',
    usersTitle: 'User Management',
    usersAdminOnly: 'Access restricted. This page is for admins only.',
    inviteUser: 'Invite/Create New User',
    userEmail: 'User (email)',
    role: 'Role',
    resetPassword: 'Reset password',
    inviteCreateUser: 'Invite / Create User',
    tempPassword: 'Temporary Password',
    displayName: 'Display Name',
    createUser: 'Create User',
    userCreatedSuccess: 'User created successfully.',
    resetPasswordTitle: 'Reset password',
    passwordUpdated: 'Password updated.',
    passwordMinLength: 'Password must be at least 6 characters',
    notLoggedIn: 'Not logged in.',
    sessionExpired: 'Session expired.',
    updateFailed: 'Update failed',
    inviteFailed: 'Invite failed',
    emailPasswordRequired: 'Email and password (min 6 chars) are required.',
    resetFailed: 'Reset failed',
    adminRole: 'Admin',
    staffRole: 'Staff',
    usersSubtext: 'View staff and reset passwords. Only admins can access this page.',
    loadingUsers: 'Loading users...',
    noUsersFound: 'No users found.',
    displayNameStaffId: 'Display Name / Staff ID',
    noName: 'No Name',
    inviteEmailPlaceholder: 'staff@example.com',
    invitePasswordPlaceholder: 'Min 6 characters',
    inviteDisplayNamePlaceholder: 'Staff 01 / Cashier Su Su',
    resetPasswordHint: 'Enter a new password for this user. They can change it later after logging in.',
    newPassword: 'New password',
    updatePassword: 'Update password',
    customerName: 'Customer Name',
    editSaleTitle: 'Edit Sale',
    editDeliveryTitle: 'Edit Delivery Sale',
    deleteSaleRecordTitle: 'Delete sale record?',
    deleteSaleRecordDesc: 'Are you sure you want to delete this invoice? Stock will be restored.',
    ordersLabel: 'orders',
    feesLabel: 'Fees',
    statusConfirmed: 'Confirmed',
    statusCheck: 'Check',
    exportLoading: 'Generating Excel file, please wait...',
    exportSuccess: 'Excel file downloaded successfully!',
    exportError: 'Export failed. Please try again.',
  },
  mm: {
    appName: 'THE MORE YOU GLOW By Ingyin POS',
    appShort: 'The More You Glow By Ingyin',
    dashboardSubtitle: 'အရောင်းစနစ်',
    loginBadge: 'The More You Glow By Ingyin သို့ ဝင်ရောက်ပါ',
    loginHeading: 'ပြန်လည်ကြိုဆိုပါတယ်',
    loginButton: 'လော့ဂ်အင်ဝင်မည်',
    loginEmail: 'အီးမေးလ်',
    loginPassword: 'လျှို့ဝှက်နံပါတ်',
    dashboardOverview: 'အထွေထွေ အမြင်',
    dashboardSubtext: 'နေ့စဉ် / လစဉ် / နှစ်အလိုက် အရောင်း အခြေအနေ။',
    inventoryTitle: 'ကုန်ပစ္စည်း စာရင်း',
    inventorySubtext: 'အရောင်းဈေးနှုန်း၊ စတော့နှင့် ကုန်ပစ္စည်းများ စီမံခန့်ခွဲရန်။',
    addProduct: 'ကုန်ပစ္စည်းအသစ် ထည့်မည်',
    searchInventoryPlaceholder: 'အမည်၊ အမျိုးအစား၊ ဘားကုဒ် ရှာရန်...',
    exportInventory: 'Excel ထုတ်ယူမည်',
    exportRecent: 'အသစ်ထည့်ထားသည့်ပစ္စည်းများ ထုတ်ယူမည်',
    downloadTemplate: 'တမ်းပလိတ် ဒေါင်းလုဒ်',
    uploadCsv: 'CSV တင်မည်',
    recentlyAdded: 'အသစ်ထည့်ထားသည့်ပစ္စည်းများ',
    itemCount: 'ပစ္စည်း',
    syncing: 'Sync လုပ်နေသည်...',
    productId: 'အိုင်ဒီ',
    image: 'ပုံ',
    name: 'အမည်',
    sku: 'ကုဒ်',
    category: 'အမျိုးအစား',
    size: 'အရွယ်အစား',
    barcode: 'ဘားကုဒ်',
    stock: 'စတော့',
    salePrice: 'ရောင်းဈေး',
    actions: 'လုပ်ဆောင်ချက်များ',
    scanBarcode: 'ဘားကုဒ် စကန်ဖတ်မည်',
    bulkUpload: 'အစုလိုက် တင်မည်',
    onlineSyncReady: 'အွန်လိုင်း စနစ် အဆင်သင့်ဖြစ်သည်။',
    offlineSyncLater: 'အော့ဖ်လိုင်းဖြစ်သည်။ ပြောင်းလဲမှုများကို နောက်မှ Sync လုပ်မည်။',
    customersTitle: 'ဖောက်သည်များ',
    customersSubtext: 'ဖောက်သည်အချက်အလက်များနှင့် သစ္စာဖောက်အခြေအနေ စီမံခန့်ခွဲရန်။',
    addCustomer: 'ဖောက်သည်အသစ် ထည့်မည်',
    edit: 'ပြင်မည်',
    delete: 'ဖျက်မည်',
    phone: 'ဖုန်း',
    phone2: 'ဖုန်း ၂',
    facebook: 'ဖေ့စ်ဘွတ်',
    address: 'လိပ်စာ',
    remark: 'မှတ်ချက်',
    totalSpent: 'စုစုပေါင်း အသုံး',
    loyalty: 'သစ္စာဖောက်',
    yes: 'ရှိ',
    no: 'မရှိ',
    schemaCacheWait: 'facebook_username ကော်လံ စကေးမာကက်ရှ် မပြီးသေးပါ။ ခဏလောက်အကြာတွင် ပြန်ကြိုးစားပါ။',
    menuMain: 'အဓိက မီနူး',
    menuCrm: 'ဖောက်သည်များ',
    menuSettingsSection: 'ဆက်တင်များ',
    menuDashboard: 'အထွေထွေ',
    menuPos: 'အရောင်းကောင်တာ',
    menuInventory: 'ကုန်ပစ္စည်း စာရင်း',
    menuShopSales: 'ဆိုင် အရောင်းမှတ်တမ်း',
    menuDeliverySales: 'ပို့ဆောင်မှု အရောင်းမှတ်တမ်း',
    menuCustomers: 'ဖောက်သည်များ',
    menuSettings: 'ဆက်တင်များ',
    menuLogout: 'ထွက်မည်',
    downloadExcel: 'Excel ဒေါင်းလုဒ်',
    refresh: 'ပြန်လည် ဆွဲယူမည်',
    searchSalesPlaceholder: 'ဘောင်ချာ၊ ဖောက်သည်၊ ဖုန်း၊ ငွေပေးချေမှု ရှာရန်...',
    searchDeliveryPlaceholder: 'ဘောင်ချာ၊ ဖောက်သည်၊ ပို့ဆောင်သူ၊ ဖုန်း ရှာရန်...',
    monthFilter: 'လ/နှစ်',
    shopSalesLogTitle: 'ဆိုင် အရောင်းမှတ်တမ်း',
    deliverySalesLogTitle: 'ပို့ဆောင်မှု အရောင်းမှတ်တမ်း',
    summaryByPayment: 'အကျဉ်းချုပ် (ငွေပေးချေမှုအလိုက်)',
    summary: 'အကျဉ်းချုပ်',
    dailyTotal: 'နေ့စဉ် စုစုပေါင်း',
    daily: 'နေ့စဉ်',
    monthly: 'လစဉ်',
    yearly: 'နှစ်အလိုက်',
    allCouriers: 'ပို့ဆောင်သူ အားလုံး',
    date: 'ရက်စွဲ',
    invoice: 'ဘောင်ချာ',
    customer: 'ဖောက်သည်',
    courier: 'ပို့ဆောင်သူ',
    deliveryFee: 'ပို့ဆောင်ခ',
    paymentMethod: 'ငွေပေးချေမှု',
    status: 'အခြေအနေ',
    totalAmount: 'စုစုပေါင်း',
    itemsSummary: 'ပစ္စည်း အကျဉ်းချုပ်',
    collected: 'ရရှိငွေ',
    netSale: 'သန့်ငွေ',
    courierFees: 'ပို့ဆောင်ခ စုစုပေါင်း',
    couriers: 'ပို့ဆောင်သူများ',
    totalLabel: 'စုစုပေါင်း',
    noSalesRecords: 'အရောင်းမှတ်တမ်း မတွေ့ပါ။',
    noDeliveryRecords: 'ပို့ဆောင်မှု မှတ်တမ်း မတွေ့ပါ။',
    noSummary: 'အကျဉ်းချုပ် မရှိပါ။',
    action: 'လုပ်ဆောင်ချက်',
    accessRestricted: 'ဝင်ရောက်ခွင့် မရှိပါ။',
    salesAdminOnly: 'အရောင်းအစီရင်ခံစာကို အက်ဒမင်သာ ကြည့်နိုင်သည်။',
    subtotal: 'အကျဉ်းချုပ်စုစုပေါင်း',
    dateRange: 'ရက်စွဲအတိုင်း',
    totalSales: 'စုစုပေါင်း အရောင်း',
    totalFees: 'စုစုပေါင်း ခများ',
    number: 'နံပါတ်',
    phoneRequired: 'ဖုန်းနံပါတ် လိုအပ်ပါသည်။',
    accessRestrictedSignIn: 'ဝင်ရောက်ခွင့် မရှိပါ။ လော့ဂ်အင်ဝင်ပါ။',
    all: 'အားလုံး',
    close: 'ပိတ်မည်',
    save: 'သိမ်းမည်',
    saving: 'သိမ်းနေသည်...',
    deleteConfirmCustomerTitle: 'ဖောက်သည်ကို ဖျက်မလား?',
    deleteConfirmCustomerDesc: 'ဤဖောက်သည်ကို ဖျက်ရန် သေချာပါသလား?',
    deleting: 'ဖျက်နေသည်...',
    customerFormTitleEdit: 'ဖောက်သည် ပြင်မည်',
    customerFormTitleAdd: 'ဖောက်သည် ထည့်မည်',
    customerFormSubtext: 'ဖောက်သည်အချက်အလက်နှင့် သစ္စာဖောက်အခြေအနေကို စီမံခန့်ခွဲရန်။',
    phonePlaceholder: 'ဖုန်းနံပါတ်',
    phone2Placeholder: 'ဒုတိယ ဖုန်း',
    customerNamePlaceholder: 'ဖောက်သည်အမည်',
    addressPlaceholder: 'လိပ်စာ',
    facebookPlaceholder: 'ဖေ့စ်ဘွတ် အမည်',
    notesPlaceholder: 'မှတ်ချက်များ',
    loyalStatus: 'သစ္စာဖောက် အခြေအနေ',
    standard: 'သာမန်',
    loyal: 'သစ္စာဖောက်',
    cancel: 'ပယ်ဖျက်မည်',
    usersTitle: 'အသုံးပြုသူ စီမံခန့်ခွဲမှု',
    usersAdminOnly: 'ဝင်ရောက်ခွင့် မရှိပါ။ ဤစာမျက်နှာကို အက်ဒမင်သာ အသုံးပြုနိုင်သည်။',
    inviteUser: 'အသုံးပြုသူ အသစ် ဖိတ်ခေါ်/ဖန်တီးမည်',
    userEmail: 'အသုံးပြုသူ (အီးမေးလ်)',
    role: 'ရာထူး',
    resetPassword: 'စကားဝှက် ပြန်သတ်မှတ်မည်',
    inviteCreateUser: 'အသုံးပြုသူ ဖိတ်ခေါ်/ဖန်တီး',
    tempPassword: 'ယာယီ စကားဝှက်',
    displayName: 'ပြသရန် အမည်',
    createUser: 'အသုံးပြုသူ ဖန်တီးမည်',
    userCreatedSuccess: 'အသုံးပြုသူ ဖန်တီးပြီးပါပြီ။',
    resetPasswordTitle: 'စကားဝှက် ပြန်သတ်မှတ်မည်',
    passwordUpdated: 'စကားဝှက် ပြောင်းပြီးပါပြီ။',
    passwordMinLength: 'စကားဝှက်သည် အနည်းဆုံး ၆ လုံး ရှိရမည်။',
    notLoggedIn: 'လော့ဂ်အင် မဝင်ရသေးပါ။',
    sessionExpired: 'စက်ရှင် သက်တမ်းကုန်ပြီ။',
    updateFailed: 'ပြင်ဆင်မှု မအောင်မြင်ပါ။',
    inviteFailed: 'ဖိတ်ခေါ်မှု မအောင်မြင်ပါ။',
    emailPasswordRequired: 'အီးမေးလ်နှင့် စကားဝှက် (အနည်းဆုံး ၆ လုံး) လိုအပ်သည်။',
    resetFailed: 'စကားဝှက် ပြန်သတ်မှတ်မှု မအောင်မြင်ပါ။',
    adminRole: 'အက်ဒမင်',
    staffRole: 'ဝန်ထမ်း',
    usersSubtext: 'ဝန်ထမ်းစာရင်းကြည့်ရှု၍ စကားဝှက်ပြန်သတ်မှတ်နိုင်သည်။ အက်ဒမင်သာ ဝင်ရောက်နိုင်သည်။',
    loadingUsers: 'အသုံးပြုသူများ လိုဒ်လုပ်နေသည်...',
    noUsersFound: 'အသုံးပြုသူ မရှိပါ။',
    displayNameStaffId: 'ပြသရန် အမည် / ဝန်ထမ်း ID',
    noName: 'အမည် မရှိ',
    inviteEmailPlaceholder: 'staff@example.com',
    invitePasswordPlaceholder: 'အနည်းဆုံး ၆ လုံး',
    inviteDisplayNamePlaceholder: 'ဝန်ထမ်း 01 / အရောင်းပေးသူ Su Su',
    resetPasswordHint: 'အသုံးပြုသူအတွက် စကားဝှက်အသစ် ထည့်ပါ။ နောက်ပိုင်းမှာ အကောင့်ဝင်ပြီး ပြန်ပြင်နိုင်သည်။',
    newPassword: 'စကားဝှက် အသစ်',
    updatePassword: 'စကားဝှက် ပြင်မည်',
    customerName: 'ဖောက်သည် အမည်',
    editSaleTitle: 'အရောင်း ပြင်မည်',
    editDeliveryTitle: 'ပို့ဆောင်မှု အရောင်း ပြင်မည်',
    deleteSaleRecordTitle: 'အရောင်းမှတ်တမ်း ဖျက်မလား?',
    deleteSaleRecordDesc: 'ဤဘောင်ချာကို ဖျက်ရန် သေချာပါသလား? စတော့ ပြန်လည်ထည့်ပါမည်။',
    ordersLabel: 'အော်ဒါ',
    feesLabel: 'ခများ',
    statusConfirmed: 'အတည်ပြု',
    statusCheck: 'စစ်ဆေးရန်',
    exportLoading: 'Excel ဖိုင် ပြုလုပ်နေသည်... ခဏစောင့်ပါ',
    exportSuccess: 'Excel ဖိုင် ဒေါင်းလုဒ် ပြီးပါပြီ!',
    exportError: 'Export မအောင်မြင်ပါ။ ထပ်မံကြိုးစားပါ။',
  },
} as const;

export type TranslationKey = keyof typeof translations.en;

export function useT() {
  const { language } = useLanguage();
  return (key: TranslationKey) => translations[language][key];
}
